#!/bin/sh
session="webdev"

tmux new-session -d -s $session
path="/home/adramax/Documents/repos/kokansky-webshop"

tmux send -t $session:1 "cd $path; clear " C-m
#tmux send -t $session:1 "ls " C-m
tmux rename-window -t zsh code

tmux new-window -t $session:2 -n 'runner'
tmux send -t $session:2 "cd $path; testshop.sh " C-m

tmux new-window -t $session:3 -n 'zsh'

tmux select-window -t $session:1
tmux send -t $session:1 "source uwsgi/bin/activate; nvim" C-m

tmux a -t $session
