#!/bin/sh

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e pulsemixer ;;
	2) amixer -D pulse set Master 1+ toggle ;;
	4) amixer set Master 3%+ -q ;;
	5) amixer set Master 3%- -q ;;
	3) notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.
- Scroll to change." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac


currentState="$(amixer get Master)"
[ $(tail -2 <<< $currentState | grep -c '\[off\]') = 2 ] && echo 🔇 && exit

vol="$(awk -F"[][]" '/Left:/ { print $2 }' <<< $currentState | sed 's/.$//')"
if [ "$vol" -gt "70" ]; then
    icon="🔊"
elif [ "$vol" -lt "30" ]; then
    icon="🔈"
else
    icon="🔉"
fi

echo "$icon$vol%"
